version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.15.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  logstash:
    image: logstash:8.15.3
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/conf:/usr/share/logstash/pipeline
      
  kibana:
    image: kibana:8.15.3
    container_name: kibana
    ports:
      - "5601:5601"
